PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    #path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^BookType/', include('apps.BookType.urls', namespace='BookType')), # 图书类别模块
    url(r'^Book/', include('apps.Book.urls', namespace='Book')), # 图书模块
    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

apps/Book/urls.py
from apps.Book.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'Book'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台图书添加
    url(r'^frontModify/(?P<barcode>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新图书
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台图书查询列表
    url(r'^frontShow/(?P<barcode>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示图片详情页

    url(r'^update/(?P<barcode>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式图书更新

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加图书
    url(r'^backModify/(?P<barcode>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新图书
    url(r'^list$', ListView.as_view(), name='list'),  # 后台图书列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除图书信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出图书信息到excel并下载
]

apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword'),  # 管理员修改密码
    url(r'^main$', MainView.as_view(), name='main')
]

apps/Book/models.py
from django.db import models
from apps.BookType.models import BookType
from tinymce.models import HTMLField


class Book(models.Model):
    barcode = models.CharField(max_length=20, default='', primary_key=True, verbose_name='图书条形码')
    bookName = models.CharField(max_length=20, default='', verbose_name='图书名称')
    bookTypeObj = models.ForeignKey(BookType,  db_column='bookTypeObj', on_delete=models.CASCADE, verbose_name='图书类别')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='图书价格')
    count = models.IntegerField(default=0,verbose_name='图书库存')
    publishDate = models.CharField(max_length=20, default='', verbose_name='出版日期')
    publish = models.CharField(max_length=20, default='', verbose_name='出版社')
    bookPhoto = models.ImageField(upload_to="img", max_length='80', verbose_name='图书图片')  #指定文件保存的路径名 系统自动创建
    bookDesc = HTMLField(verbose_name='图书简介')
    bookFile = models.FileField(upload_to='file', max_length='100', verbose_name='图书文件')

    class Meta:
        db_table = 't_Book'
        verbose_name = '图书信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        book = {
            "barcode": self.barcode,
            "bookName": self.bookName,
            'bookTypeObj': self.bookTypeObj.bookTypeName,
            'bookTypeObjPri': self.bookTypeObj.bookTypeId,
            'price': self.price,
            'count': self.count,
            'publishDate': self.publishDate,
            'publish': self.publish,
            'bookPhoto': self.bookPhoto.url,
            'bookDesc': self.bookDesc,
            'bookFile': self.bookFile.url
        }
        return book

apps/Book/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.Book.models import Book
from apps.BookType.models import BookType
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台图书添加
    def primaryKeyExist(self, barcode):  # 判断主键是否存在
        try:
            Book.objects.get(barcode=barcode)
            return True
        except Book.DoesNotExist:
            return False

    def get(self,request):
        bookTypes = BookType.objects.all()  # 获取所有图书类型
        context = {
            'bookTypes': bookTypes,
        }
        # 使用模板
        return render(request, 'Book/book_frontAdd.html', context)

    def post(self,request):
        barcode = request.POST.get('book.barcode') # 判断图书条形码是否存在
        if self.primaryKeyExist(barcode):
            return JsonResponse({'success': False, 'message': '图书条形码已经存在'})

        book = Book() # 新建一个图书对象然后获取参数
        book.barcode = barcode
        book.bookName = request.POST.get('book.bookName')
        book.bookTypeObj = BookType.objects.get(bookTypeId=int(request.POST.get('book.bookTypeObj.bookTypeId')))
        book.price = float(request.POST.get('book.price'))
        book.count = int(request.POST.get('book.count'))
        book.publishDate = request.POST.get('book.publishDate')
        book.publish = request.POST.get('book.publish')
        try:
            book.bookPhoto = self.uploadImageFile(request,'book.bookPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        book.bookDesc = request.POST.get('book.bookDesc')
        book.bookFile = self.uploadCommonFile(request,'book.bookFile')
        book.save() # 保存图书信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改图书
    def get(self, request, barcode):
        context = {"barcode": barcode}
        return render(request, 'Book/book_frontModify.html', context)


class FrontListView(BaseView):  # 前台图书查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self,request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        barcode = self.getStrParam(request, 'barcode')
        bookName = self.getStrParam(request, 'bookName')
        publishDate = self.getStrParam(request, 'publishDate')
        bookTypeObj_bookTypeId = self.getIntParam(request, 'bookTypeObj.bookTypeId')
        # 然后条件组合查询过滤
        book = Book.objects.all()
        if barcode != '':
            book = book.filter(barcode__contains=barcode)
        if bookName != '':
            book = book.filter(bookName__contains=bookName)
        if publishDate != '':
            book = book.filter(publishDate__contains=publishDate)
        if bookTypeObj_bookTypeId != '0':
            book = book.filter(bookTypeObj=bookTypeObj_bookTypeId)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(book, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        books_page = self.paginator.page(self.currentPage)

        # 获取所有图书类型
        bookTypes = BookType.objects.all()
        # 构造模板需要的参数
        context = {
            'bookTypes': bookTypes,
            'books_page': books_page,
            'barcode': barcode,
            'bookName': bookName,
            'publishDate': publishDate,
            'bookTypeObj_bookTypeId': int(bookTypeObj_bookTypeId),
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'Book/book_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示图片详情页
    def get(self, request, barcode):
        bookTypes = BookType.objects.all()
        # 查询需要显示的图书对象
        book = Book.objects.get(barcode=barcode)
        context = {
            'bookTypes': bookTypes,
            'book': book
        }
        # 渲染模板显示
        return render(request, 'Book/book_frontshow.html', context)


class UpdateView(BaseView):  # Ajax方式图书更新
    def get(self, request, barcode):
        # GET方式请求查询图书对象并返回图书json格式
        book = Book.objects.get(barcode=barcode)
        return JsonResponse(book.getJsonObj())

    def post(self, request, barcode):
        # POST方式提交图书修改信息更新到数据库
        book = Book.objects.get(barcode=barcode)
        book.bookName = request.POST.get('book.bookName')
        book.bookTypeObj = BookType.objects.get(bookTypeId=int(request.POST.get('book.bookTypeObj.bookTypeId')))
        book.price = float(request.POST.get('book.price'))
        book.count = int(request.POST.get('book.count'))
        book.publishDate = request.POST.get('book.publishDate')
        book.publish = request.POST.get('book.publish')
        try:
            bookPhotoName = self.uploadImageFile(request, 'book.bookPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        if bookPhotoName != 'img/NoImage.jpg':
            book.bookPhoto = bookPhotoName

        book.bookDesc = request.POST.get('book.bookDesc')
        bookFileName = self.uploadCommonFile(request, 'book.bookFile')
        if bookFileName != 'file/NoFile.jpg':
            book.bookFile = bookFileName

        book.save()
        return JsonResponse({'success': True, 'message': '保存成功'})


class AddView(BaseView):  # 后台添加图书
    def primaryKeyExist(self, barcode):  # 判断主键是否存在
        try:
            Book.objects.get(barcode=barcode)
            return True
        except Book.DoesNotExist:
            return False

    def get(self, request):
        # 获取所有图书类型
        bookTypes = BookType.objects.all()
        context = {
            'bookTypes': bookTypes,
        }
        # 渲染显示模板界面
        return render(request, 'Book/book_add.html', context)

    def post(self, request):
        # POST方式处理图书添加业务
        barcode = request.POST.get('book.barcode')
        if self.primaryKeyExist(barcode):
            return JsonResponse({'success': False, 'message': '图书条形码已经存在'})
        # 新建一个图书对象然后收集图书参数
        book = Book()
        book.barcode = barcode
        book.bookName = request.POST.get('book.bookName')
        book.bookTypeObj = BookType.objects.get(bookTypeId=int(request.POST.get('book.bookTypeObj.bookTypeId')))
        book.price = float(request.POST.get('book.price'))
        book.count = int(request.POST.get('book.count'))
        book.publishDate = request.POST.get('book.publishDate')
        book.publish = request.POST.get('book.publish')
        try:
            book.bookPhoto = self.uploadImageFile(request, 'book.bookPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        book.bookDesc = request.POST.get('book.bookDesc')
        book.bookFile = self.uploadCommonFile(request, 'book.bookFile')
        book.save()  # 这里提交更新到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新图书
    def get(self, request, barcode):
        context = {"barcode": barcode}
        return render(request, 'Book/book_modify.html', context)


class ListView(BaseView):  # 后台图书列表
    def get(self, request):
        # 使用模板
        return render(request, 'Book/book_query_result.html')

    def post(self,request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        barcode = self.getStrParam(request, 'barcode')
        bookName = self.getStrParam(request, 'bookName')
        publishDate = self.getStrParam(request, 'publishDate')
        bookTypeObj_bookTypeId = self.getIntParam(request, 'bookTypeObj.bookTypeId')
        # 然后条件组合查询过滤
        books = Book.objects.all()
        if barcode != '':
            books = books.filter(barcode__contains=barcode)
        if bookName != '':
            books = books.filter(bookName__contains=bookName)
        if publishDate != '':
            books = books.filter(publishDate__contains=publishDate)
        if bookTypeObj_bookTypeId != '0':
            books = books.filter(bookTypeObj=bookTypeObj_bookTypeId)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(books, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        books_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        bookList = []
        for book in books_page:
            book = book.getJsonObj()
            bookList.append(book)
        # 构造模板页面需要的参数
        book_res = {
            'rows': bookList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(book_res, json_dumps_params={'ensure_ascii':False})


class DeletesView(BaseView):  # 删除图书信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        barcodes = self.getStrParam(request, 'barcodes')
        barcodes = barcodes.split(',')
        count = 0
        try:
            for barcode in barcodes:
                Book.objects.get(barcode=barcode).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库删除发生错误！'
            success = False
        return JsonResponse({"success": success, "message": message})


class OutToExcelView(BaseView):  # 导出图书信息到excel并下载
    def get(self,request):
        # 收集查询参数
        barcode = self.getStrParam(request, 'barcode')

templates/Book/book_frontAdd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>图书添加</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="col-md-12 wow fadeInLeft">
		<ul class="breadcrumb">
  			<li><a href="{% url 'Index:index' %}">首页</a></li>
  			<li><a href="{% url 'Book:frontList' %}">图书管理</a></li>
  			<li class="active">添加图书</li>
		</ul>
		<div class="row">
			<div class="col-md-10">
		      	<form class="form-horizontal" name="bookAddForm" id="bookAddForm" enctype="multipart/form-data" method="post"  class="mar_t15">
				    {% csrf_token %}
                    <div class="form-group">
					 <label for="book_barcode" class="col-md-2 text-right">图书条形码:</label>
					 <div class="col-md-8">
					 	<input type="text" id="book_barcode" name="book.barcode" class="form-control" placeholder="请输入图书条形码">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="book_bookName" class="col-md-2 text-right">图书名称:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="book_bookName" name="book.bookName" class="form-control" placeholder="请输入图书名称">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="book_bookTypeObj_bookTypeId" class="col-md-2 text-right">图书所在类别:</label>
				  	 <div class="col-md-8">
					    <select id="book_bookTypeObj_bookTypeId" name="book.bookTypeObj.bookTypeId" class="form-control">
                            {% for bookType in bookTypes %}
                            <option value="{{ bookType.bookTypeId }}">{{ bookType.bookTypeName }}</option>
                            {% endfor %}
					    </select>
				  	 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="book_price" class="col-md-2 text-right">图书价格:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="book_price" name="book.price" class="form-control" placeholder="请输入图书价格">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="book_count" class="col-md-2 text-right">库存:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="book_count" name="book.count" class="form-control" placeholder="请输入库存">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="book_publishDateDiv" class="col-md-2 text-right">出版日期:</label>
				  	 <div class="col-md-8">
		                <div id="book_publishDateDiv" class="input-group date book_publishDate col-md-12" data-link-field="book_publishDate" data-link-format="yyyy-mm-dd">
		                    <input class="form-control" id="book_publishDate" name="book.publishDate" size="16" type="text" value="" placeholder="请选择出版日期" readonly>
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
		                </div>
				  	 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="book_publish" class="col-md-2 text-right">出版社:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="book_publish" name="book.publish" class="form-control" placeholder="请输入出版社">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="book_bookPhoto" class="col-md-2 text-right">图书图片:</label>
				  	 <div class="col-md-8">
					    <img  class="img-responsive" id="book_bookPhotoImg" border="0px"/><br/>
					    <input id="bookPhoto" name="book.bookPhoto" type="file" size="50" />
				  	 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="book_bookDesc" class="col-md-2 text-right">图书简介:</label>
				  	 <div class="col-md-8">
							    <textarea name="book.bookDesc" id="book_bookDesc" style="width:100%;height:300px;"></textarea>
                     </div>
				  </div>
				  <div class="form-group">
				  	 <label for="book_bookFile" class="col-md-2 text-right">图书文件:</label>
				  	 <div class="col-md-8">
					    <a id="book_bookFileImg" border="0px"></a><br/>
					    <input id="bookFile" name="book.bookFile" type="file" size="50" />
				  	 </div>
				  </div>
		          <div class="form-group">
		             <span class="col-md-2""></span>
		             <span onclick="ajaxBookAdd();" class="btn btn-primary bottom5 top5">添加</span>
		          </div>
		          <style>#bookAddForm .form-group {margin:5px;}  </style>
				</form>
			</div>
			<div class="col-md-2"></div>
	    </div>
	</div>
</div>
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrapvalidator/js/bootstrapValidator.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>

<script src="{% static 'tiny_mce/tiny_mce.js' %}"></script>

<script>
    //实例化图书描述编辑器
    tinyMCE.init({
        selector: "#book_bookDesc",
        theme: 'advanced',
        language: "zh",
        strict_loading_mode: 1,
    });

	//提交添加图书信息
	function ajaxBookAdd() {
	    $("#book_bookDesc").text(tinyMCE.editors['book_bookDesc'].getContent());
		//提交之前先验证表单
		$("#bookAddForm").data('bootstrapValidator').validate();
		if(!$("#bookAddForm").data('bootstrapValidator').isValid()){
			return;
		}
		jQuery.ajax({
			type : "post",
			url : "{% url 'Book:frontAdd' %}",
			dataType : "json" ,
			data: new FormData($("#bookAddForm")[0]),
			success : function(obj) {
				if(obj.success){
					alert("保存成功！");
                    location.reload()
				} else {
					alert(obj.message);
				}
			},
			processData: false,
			contentType: false,
		});
	}
$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();
	//验证图书添加表单字段
	$('#bookAddForm').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			"book.barcode": {
				validators: {
					notEmpty: {
						message: "图书条形码不能为空",
					}
				}
			},
			"book.bookName": {
				validators: {
					notEmpty: {
						message: "图书名称不能为空",
					}
				}
			},
			"book.price": {
				validators: {
					notEmpty: {
						message: "图书价格不能为空",
					},
					numeric: {
						message: "图书价格不正确"
					}
				}
			},
			"book.count": {
				validators: {
					notEmpty: {
						message: "库存不能为空",
					},
					integer: {
						message: "库存不正确"
					}
				}
			},
			"book.publishDate": {
				validators: {
					notEmpty: {
						message: "出版日期不能为空",
					}
				}
			},
		}
	});

	/*
	//初始化图书所在类别下拉框值
	$.ajax({
		url: basePath + "BookType/listAll",
		type: "get",
		success: function(bookTypes,response,status) {
			$("#book_bookTypeObj_bookTypeId").empty();
			var html="";
    		$(bookTypes).each(function(i,bookType){
    			html += "<option value='" + bookType.bookTypeId + "'>" + bookType.bookTypeName + "</option>";
    		});
    		$("#book_bookTypeObj_bookTypeId").html(html);
    	}
	});
	*/
	//出版日期组件
	$('#book_publishDateDiv').datetimepicker({
		language:  'zh-CN',  //显示语言
		format: 'yyyy-mm-dd',
		minView: 2,
		weekStart: 1,
		todayBtn:  1,
		autoclose: 1,
		minuteStep: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0
	}).on('hide',function(e) {
		//下面这行代码解决日期组件改变日期后不验证的问题
		$('#bookAddForm').data('bootstrapValidator').updateStatus('book.publishDate', 'NOT_VALIDATED',null).validateField('book.publishDate');
	});
})
</script>
</body>
</html>

templates/Book/book_frontshow.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
  <TITLE>查看图书详情</TITLE>
  <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
</head>
<body style="margin-top:70px;">
{% include 'header.html' %}
<div class="container">
	<ul class="breadcrumb">
  		<li><a href="{% url 'Index:index' %}">首页</a></li>
  		<li><a href="{% url 'Book:frontList' %}">图书信息</a></li>
  		<li class="active">详情查看</li>
	</ul>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4 text-right bold">图书条形码:</div>
		<div class="col-md-10 col-xs-6">{{ book.barcode }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4 text-right bold">图书名称:</div>
		<div class="col-md-10 col-xs-6">{{ book.bookName }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4 text-right bold">图书所在类别:</div>
		<div class="col-md-10 col-xs-6">{{ book.bookTypeObj.bookTypeName }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4 text-right bold">图书价格:</div>
		<div class="col-md-10 col-xs-6">{{ book.price }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4 text-right bold">库存:</div>
		<div class="col-md-10 col-xs-6">{{ book.count }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4 text-right bold">出版日期:</div>
		<div class="col-md-10 col-xs-6">{{ book.publishDate }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4 text-right bold">出版社:</div>
		<div class="col-md-10 col-xs-6">{{ book.publish }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4 text-right bold">图书图片:</div>
		<div class="col-md-10 col-xs-6"><img class="img-responsive" src="{{ book.bookPhoto.url }}"  border="0px"/></div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4 text-right bold">图书简介:</div>
		<div class="col-md-10 col-xs-6">{{ book.bookDesc | safe }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4 text-right bold">图书文件:</div>
		<div class="col-md-10 col-xs-6">
            {% if book.bookFile == 'file/NoFile.jpg' %}
            暂无文件
            {% else %}
            <a href="{{ book.bookFile.url }}" target="_blank"><script>document.write(decodeURIComponent('{{ book.bookFile.url }}'));</script></a>
            {% endif %}

        </div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4"></div>
		<div class="col-md-6 col-xs-6">
			<button onclick="history.back();" class="btn btn-primary">返回</button>
		</div>
	</div>
</div>
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script>
$(function(){
        /*小屏幕导航点击关闭菜单*/
        $('.navbar-collapse a').click(function(){
            $('.navbar-collapse').collapse('hide');
        });
        new WOW().init();
 })
 </script>
</body>
</html>